use_frameworks!

platform :ios, '10.0'

target 'RxPageViewController_Example' do
  pod 'RxPageViewController', :path => '../'

  target 'RxPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
